trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Npm@1
  displayName: Install packages
  inputs:
    command: 'install'

- task: Npm@1
  displayName: Build
  inputs:
    command: 'custom'
    customCommand: 'run prepare'

- task: Npm@1
  displayName: Test
  inputs:
    command: 'custom'
    customCommand: 'run test'

- task: Npm@1
  displayName: Publish
  inputs:
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: '623aae93-2e21-41ba-9f1c-07d5a77f7965'